package db

import (
	"testing"
)

func TestSecurityEncryptDecrypt(t *testing.T) {
	secret := "test_master_salt_key_123"
	pwd := "mypassword123456"

	enc := EncryptPassword(pwd, secret)
	if !IsEncrypted(enc) {
		t.Fatalf("expected encrypted prefix, got: %s", enc)
	}

	dec := DecryptPassword(enc, secret)
	if dec != pwd {
		t.Fatalf("expected decrypted %s, got: %s", pwd, dec)
	}
}

func TestSecurityDecryptPythonFernetToken(t *testing.T) {
	// Token generated by Python's cryptography.fernet for user zalupa@msn.local
	pythonToken := "enc:v1:gAAAAABqrGA25R_k7G2IdihYPfcNo2JO0f6Shg_Y9LmBwRHzosTqFC0h4BQLJOGILVvvJ26CtNGY5wRM3AGhfIszfL9PRUjOaw=="
	secret := DefaultFallbackKey

	dec := DecryptPassword(pythonToken, secret)
	expected := "543451000"
	if dec != expected {
		t.Fatalf("Python token decryption failed! expected: %s, got: %s", expected, dec)
	}
}
